/// <reference types="node" />
// Usage: node scripts/radio-pool.ts            (rewrites src/shared/radiopool.ts)
// Finds, for each versus map, the spots a hidden radio may sit: standable and reachable from a spawn (the map-lint rasters), tucked into a corner or
// alcove (a wall within 100 px on a run of three to five of the eight compass directions, never on opposite sides, so not a lane), and well clear of
// spawn pads and capture zones. The client picks two to four of these each round by seed (src/shared/radio.ts `hiddenRadios`).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { MAPS, ROTATION, ZONE_RADIUS, type MapDef, type MapId } from '../src/shared/maps.ts';
import { cellsIn, CELL, flood, standable } from './map-lint.ts';

/** Every map the versus modes (FFA, TDM, DOM, BR) rotate through. */
export const VERSUS_MAPS: readonly MapId[] = [...new Set((['FFA', 'TDM', 'DOM', 'BR'] as const).flatMap((m) => ROTATION[m]))];
export const SPAWN_CLEAR = 220;
export const ZONE_CLEAR = ZONE_RADIUS + 160;
export const TUCK_REACH = 4;
export const POOL_GAP = 450;
export const POOL_MAX = 30;
const DIRS = [[1, 0], [1, 1], [0, 1], [-1, 1], [-1, 0], [-1, -1], [0, -1], [1, -1]] as const;

/** How many of the eight directions meet a wall within `TUCK_REACH` cells, and whether they form one arc with no opposite pair. */
export function tuck(free: Uint8Array, n: number, i: number, j: number): { blocked: number; arc: boolean } {
  const hit = DIRS.map(([dx, dy]) => {
    for (let k = 1; k <= TUCK_REACH; k++) {
      const x = i + dx * k, y = j + dy * k;
      if (x < 0 || y < 0 || x >= n || y >= n || !free[y * n + x]) return true;
    }
    return false;
  });
  const blocked = hit.filter(Boolean).length;
  const opposite = hit.some((h, d) => h && hit[(d + 4) % 8]);
  let runs = 0;
  for (let d = 0; d < 8; d++) if (hit[d] && !hit[(d + 7) % 8]) runs++;
  return { blocked, arc: blocked >= 3 && blocked <= 5 && !opposite && runs === 1 };
}

const farFromRect = (x: number, y: number, r: { x: number; y: number; w: number; h: number }, d: number) => {
  const dx = Math.max(r.x - x, 0, x - (r.x + r.w)), dy = Math.max(r.y - y, 0, y - (r.y + r.h));
  return Math.hypot(dx, dy) >= d;
};

export function poolFor(def: MapDef): [number, number][] {
  const n = Math.floor(def.size / CELL);
  const free = standable(def, n);
  const spawns = [...def.spawns.red, ...def.spawns.blue, ...def.spawns.ffa];
  const reached = new Uint8Array(n * n);
  flood(free, n, spawns.flatMap((r) => cellsIn(r, n)), reached);
  const found: { x: number; y: number; score: number }[] = [];
  const margin = 4;
  for (let j = margin; j < n - margin; j++) for (let i = margin; i < n - margin; i++) {
    const c = j * n + i;
    if (!free[c] || !reached[c]) continue;
    const t = tuck(free, n, i, j);
    if (!t.arc) continue;
    const x = (i + 0.5) * CELL, y = (j + 0.5) * CELL;
    if (!spawns.every((r) => farFromRect(x, y, r, SPAWN_CLEAR))) continue;
    if (def.zones.some((z) => Math.hypot(z.x - x, z.y - y) < ZONE_CLEAR)) continue;
    found.push({ x, y, score: t.blocked + ((i * 7 + j * 13) % 5) / 10 });
  }
  found.sort((a, b) => b.score - a.score || a.y - b.y || a.x - b.x);
  const out: [number, number][] = [];
  for (const f of found) {
    if (out.length >= POOL_MAX) break;
    if (out.every(([x, y]) => Math.hypot(x - f.x, y - f.y) >= POOL_GAP)) out.push([f.x, f.y]);
  }
  return out.sort((a, b) => a[1] - b[1] || a[0] - b[0]);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const lines = ['// Generated by scripts/radio-pool.ts (node scripts/radio-pool.ts). Do not edit by hand.', '// Hidden-radio spots per versus map: standable, reachable, tucked into corners and alcoves, clear of spawns and zones.', 'export const RADIO_POOL: Readonly<Record<string, readonly (readonly [number, number])[]>> = {'];
  for (const id of VERSUS_MAPS) {
    const pool = poolFor(MAPS[id]);
    console.log(id.padEnd(10), pool.length);
    lines.push(`  ${id}: [${pool.map(([x, y]) => `[${x}, ${y}]`).join(', ')}],`);
  }
  lines.push('};', '');
  writeFileSync(fileURLToPath(new URL('../src/shared/radiopool.ts', import.meta.url)), lines.join('\n'));
}
