/**
 * What the soldiers say. Each personality has a pool of idle lines (said when nothing is happening) and a few lines for each
 * context tag (said when that tag is fresh). Lines are short enough for a two-line bubble (at most 48 characters), PG-13, and in the
 * toy-soldier diorama's world. The `|` separator is only a writing convenience; no line contains one.
 */

export const TAGS = [
  'justSpawned', 'justKilled', 'closeCall', 'onStreak', 'respawned', 'lowHealth', 'longIdle', 'hunted', 'goldenGun', 'nearBarrel',
  'airdropInbound', 'zombiesDay', 'zombiesNight', 'coreDamaged', 'roundEndingSoon', 'wonRound', 'lostRound',
] as const;
export type Tag = (typeof TAGS)[number];

export const PERSONALITY_IDS = ['veteran', 'rookie', 'philosopher', 'comedian', 'hype', 'monk', 'conspiracist', 'tactician', 'poet'] as const;
export type PersonalityId = (typeof PERSONALITY_IDS)[number];

export type Personality = { id: PersonalityId; name: string; funny: boolean; idle: readonly string[]; tags: Readonly<Record<Tag, readonly string[]>> };

export const MAX_LINE = 48;

const L = (s: string): string[] => s.split('|').map((x) => x.trim()).filter(Boolean);
const T = (o: Record<Tag, string>): Record<Tag, string[]> => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, L(v)])) as Record<Tag, string[]>;

export const PERSONALITIES: readonly Personality[] = [
  {
    id: 'veteran', name: 'Grizzled Veteran', funny: false,
    idle: L(`Seen worse. Not much worse.|Back in my day the crates were smaller.|Held this exact spot for a whole minute once.|Quiet. Too quiet. Fine, normal quiet.|Never trust a corner. Corners lie.|Lost three helmets in the Plaza campaign.|Reload when you can, not when you must.|My knees are plastic. They still hurt.|Every barrel is somebody's bad idea.|Slept in a crate once. Ten out of ten.|Heard a footstep in '09. Was my own.|Walls are friends. Open ground is a lecture.|I name my bullets. Gerald is the loud one.|Smells like gunpowder and fresh paint.|Old soldiers never die. They respawn.|Count your mags, then count them again.|Been shot at by better. And worse.|Rule one: stay out of the open.|Cold coffee, warm barrel. Good day.|Medals are just heavy paperweights.|The Boneyard still owes me a boot.|Never run on a full mag of confidence.|The new recruits look so glossy.|Twenty years in the box. Still smells of card.|My painted-on scar is real to me.|Peace is just a long reload.|Stay low, stay boring, stay alive.|That crate has seen things.|Kept my gun clean. Everything else is a mess.|Eat when you can. Which is never. I'm plastic.|Kid, the floor is just bone-colored lava.|Hear that? Nothing. Beautiful.|I could do this blindfolded. Have. Hurt.|Every war ends. Mine ends at the toy chest.|Fought a rubber duck once. Never again.`),
    tags: T({
      justSpawned: 'Another day, another drop-in.|Boots down. Eyes up.|Fresh paint. Same old war.',
      justKilled: "That one's for the old crew.|Clean. Don't get proud.|One less to worry about.",
      closeCall: "Seen closer. Not by much.|Wasn't my day. Wasn't theirs either.",
      onStreak: "Don't count 'em. Bad luck.|Hot streak. Cold heart.",
      respawned: "Got sloppy. Won't happen twice.|Dust off. Go again.",
      lowHealth: 'Walk it off. Plastic heals. Mostly.|Just a scratch. A big one.',
      longIdle: 'Waiting is a skill. I am very skilled.|Holding position. And a grudge.',
      hunted: "Everybody wants the old man's gun.|Hunted? Story of my life.",
      goldenGun: 'Shiny. Shiny gets people killed.|Gold gun. Heavy on the conscience.',
      nearBarrel: "Don't stand by the barrel. Learn from me.|Barrels. Never again. Okay, again.",
      airdropInbound: 'Supply drop. Free things have strings.|Plane is up. Watch the sky and your back.',
      zombiesDay: 'Daylight. Fix the wall, sharpen the nerves.|Calm before the horde. Stack scrap.',
      zombiesNight: 'Night shift. My favorite. Not really.|Hold the line till sunrise.',
      coreDamaged: "The Bastion's taking hits. Dig in.|Protect the core. That's the whole job.",
      roundEndingSoon: "Clock's running. Make it count.|Last minutes. Where stories start.",
      wonRound: "Won one. Doesn't make me soft.|Good round. Don't tell the rookies.",
      lostRound: "Lost one. We'll get the next.|Retreat is advance with sad music.",
    }),
  },
  {
    id: 'rookie', name: 'Nervous Rookie', funny: true,
    idle: L(`Was that a footstep? Please be a footstep.|Is my helmet on straight? It's painted on.|Nobody told me there'd be bullets.|I'm fine. Totally fine. Hello.|Mom thinks I'm in logistics.|We have a plan, right? We have a plan.|I only learned to aim this morning.|Which end of the gun is the scary end?|Don't look at me. Look at them. Not me.|I counted my bullets. Then forgot the number.|That crate moved. Did that crate move?|Stay calm. Stay calm. Stay... calm.|Sarge said breathe. I forgot how.|My hands are shaking. That's the paint.|Is it bad that I named my gun Kevin?|I've never been this far from the box.|Everyone here is so tall. And plastic.|I should have stayed in the shop window.|I think I left the stove on.|Why is everything so loud?|Okay okay okay okay okay okay.|I read the manual. It was two pages.|Please let it be a quiet shift.|I got a participation medal once.|I just want to be a shelf ornament.|Everybody says stay low. Low where?|Do bullets know I'm new?|I packed snacks. I have no mouth.|Was that thunder? Gunfire? Both?|If I stand still, maybe I'm furniture.|My brave face is painted on too.|Vet said good luck. Why luck?|Left, right, left. Wait, that's walking.|Oh no, I'm in the middle of the map.|Does this helmet make me look killable?|I was promised a desk job.`),
    tags: T({
      justSpawned: 'Oh no, I\'m here again.|Ready! Probably! Maybe!|Okay, deep breath. Going in.',
      justKilled: 'Did I do that?! Sorry!|I got one! Don\'t tell anyone!|Wow! Was that me?',
      closeCall: "I'm alive?! I'm alive!|That was MY LIFE. That was it.",
      onStreak: 'Why does this keep working?|Am I good? Is this being good?',
      respawned: 'Ow. Okay. Again. Gently.|Headache. Painted on, but still.',
      lowHealth: 'I feel... not great? Medic?|Is red good? I think red is bad.',
      longIdle: "I'll just wait here. Forever. Fine.|Standing very still. Very, very still.",
      hunted: 'Why is everyone looking at me?!|They can see me! They CAN SEE ME!',
      goldenGun: "It's so shiny. I'm scared to use it.|Is this gun mine? Do I give it back?",
      nearBarrel: 'That barrel is looking at me weird.|Red barrel. Red means no. I think.',
      airdropInbound: 'Is that a plane?! Is it for me?!|Free stuff from the sky? Suspicious.',
      zombiesDay: "It's quiet. I hate it. Stay quiet.|Building things! I like building things.",
      zombiesNight: 'Why are they all so GREEN?!|Zombies. Nobody said zombies. Why zombies?',
      coreDamaged: "The Bastion's hurt! Is it okay?!|Someone fix the thing! The thing!",
      roundEndingSoon: 'Almost over! I might survive this!|Clock is low! Just do not die.',
      wonRound: "We won?! I didn't even do anything!|Mom's gonna be so proud!",
      lostRound: 'We lost? Was that my fault?|I will do better. Sorry. Sorry.',
    }),
  },
  {
    id: 'philosopher', name: 'Philosopher', funny: false,
    idle: L(`If I respawn, am I still me?|Wonder what I was like in my past life.|Do the walls choose us, or we the walls?|A crate is just a wall that gave up.|Every bullet is a question. Death answers.|What if the arena is the only world?|To respawn is to be forgiven, repeatedly.|Time passes. I'm not sure it knows me.|Are we the toys, or is the box the toy?|I think, therefore I should duck.|The floor is bone. What does that say of us?|Who paints the sky? Who sweeps the floor?|If a soldier falls and no one is watching...|Is courage just fear with better posture?|Yesterday, a plastic idea. Today, a soldier.|We are all just waiting for the next round.|Somewhere, a child decides my fate. Hi.|The simulation is kind, but not gentle.|Why do we fight? Because the score demands it.|The horizon is a suggestion.|My shadow always falls to the right. Always.|Does the barrel fear its own explosion?|Every ending is a spawn point in disguise.|One must imagine the sentry happy.|What is a medal but a shiny memory?|Death is a door. The door is respawn.|I contain multitudes. Mostly plastic.|The walls remember who leaned on them.|Does the score keep me, or I it?|I have been here before. Probably Tuesday.|Is the map a prison or a stage?|Silence is also an answer.|Who am I when nobody is shooting at me?|Is this my first life, or my fortieth?|What does the crate dream of?`),
    tags: T({
      justSpawned: 'Born again. The universe has a sense of humor.|A new life. Same old questions.',
      justKilled: 'We all return to the box, eventually.|I regret nothing. I will, later.',
      closeCall: 'I felt my own mortality. Briefly.|Life flashed by. Bad editing.',
      onStreak: 'Is it fate, or just good aim?|Streaks are temporary. So is everything.',
      respawned: 'Death was brief. Philosophically useful.|Back already. Reincarnation is fast here.',
      lowHealth: 'Is this the end? Or the middle? Or lunch?|My health is a metaphor now.',
      longIdle: 'I stand still. The world moves. Or I do.|Stillness. Rare in a place like this.',
      hunted: 'To be hunted is to be seen. To be seen...|Fame is just a target on the back.',
      goldenGun: 'Gold: the most dangerous kind of wealth.|The golden gun owns me, not I it.',
      nearBarrel: 'Behold: a bomb pretending to be furniture.|A barrel. Potential energy with a lid.',
      airdropInbound: 'Gifts from the sky. The gods do provide.|The sky delivers. Rarely kindly.',
      zombiesDay: 'By day we build. By night we are tested.|Daylight is just borrowed time.',
      zombiesNight: 'The dead walk. As above, so below.|Night. The oldest enemy.',
      coreDamaged: 'The Bastion bleeds. What are we without it?|Everything we build can break.',
      roundEndingSoon: 'Time grows short. As it always does.|The round ends. Another begins. Always.',
      wonRound: 'Victory. How hollow. How pleasant.|We won. What does a win win us?',
      lostRound: 'Defeat teaches. I am tired of learning.|To lose is to learn. I am very educated.',
    }),
  },
  {
    id: 'comedian', name: 'Comedian', funny: true,
    idle: L(`All these boxes look the same.|Why do I smell like plastic?|My helmet is painted on. I checked.|I ordered a war. This isn't what I expected.|Fun fact: I have no elbows.|Who left a barrel here? Classic barrel.|Why do we say cover? I want a duvet.|If this is a diorama, where's the tip jar?|Sir, this is a crate.|I have a gun and no pockets. Priorities?|Is it me, or is the floor very beige?|I tripped on nothing. Nothing is dangerous.|I'd tell a reload joke, but it takes a while.|You ever just stand next to a wall? Great wall.|Good news: still not dead. Bad news: later.|Ten out of ten would respawn again.|The crates are judging my aim. Fair.|Why is it called a magazine? No articles.|Dropped my gun once. It didn't say ow.|My name tag says Soldier. So creative.|I'm not lost. I'm exploring aggressively.|Walking is just falling with commitment.|Shoutout to my left foot. Perfect record.|I never read the terms of service. Of war.|Zero stars. Would not recommend the war.|Do we get a lunch break? I have no mouth.|My aim is like my cooking. Optimistic.|Is this a casual war or a formal one?|I'm a people person. People ruin it.|Have you tried NOT getting shot? Underrated.|Bullet holes: free ventilation for crates.|Why are the walls always where I run?|My shadow keeps following me. Creepy.|Tiny plastic man, big plastic feelings.|I'm 90% paint and 10% opinions.`),
    tags: T({
      justSpawned: "Hello! I'm here for the war, as scheduled.|Spawned in! Please clap.",
      justKilled: 'Sorry! Was that your head? My bad.|Sorry, did you need that? Too late.',
      closeCall: 'Almost died. Would not recommend.|That was close. My paint nearly chipped.',
      onStreak: "I'm on fire. Not literally. Hopefully.|Streak! Please hold your applause.",
      respawned: "I'm back! Missed me? Nobody missed me.|Died quickly. A personal best, maybe.",
      lowHealth: 'Feeling great! (I am not great.)|I have had better days. Even yesterday.',
      longIdle: 'Just standing here. Making it awkward.|Nothing happening. My favorite genre.',
      hunted: "Everyone's staring. Is my fly open?|I'm famous! This is awful.",
      goldenGun: "I'm holding gold. Be nice to me.|Golden gun. Finally, an accessory.",
      nearBarrel: "Don't shoot the barrel. Please. Rude.|Barrel. Every party needs a bang.",
      airdropInbound: "Free stuff! Why isn't war always like this?|A plane! Is it bringing pizza?",
      zombiesDay: 'Daytime! Time to build a wall. And ego.|No zombies. Is this peace? Boring.',
      zombiesNight: "Zombies! Gross. Where's my lawyer?|They want my brain. Joke's on them.",
      coreDamaged: "Somebody's kicking the Bastion. Not cool.|The Bastion's wobbling. So am I.",
      roundEndingSoon: "Clock's low! Look busy!|Almost done. Pretend I did something.",
      wonRound: 'We won! I contributed emotional support.|Victory! I would like to thank my gun.',
      lostRound: 'We lost. Does anyone have a refund?|Great loss. Terrific. Love that for us.',
    }),
  },
  {
    id: 'hype', name: 'Hype Gamer', funny: true,
    idle: L(`Chat, are we cracked yet?|POG. Everything is pog.|Let's gooo, nobody's here yet!|Gaming. That's it. That's the quote.|Lowkey one-tap energy right now.|Today's the day. Every day's the day.|Brain is big. Aim is bigger.|My K/D could be better. Let's fix that.|Warming up the thumbs. And the soul.|I'm built different. Mostly plastic.|Sub goal: not die. Going great.|Don't forget to like and subscribe to my gun.|Reload speed? Unreal. Check the clip.|GG in advance, just in case.|Peak performance incoming. Any second.|Main character energy, side character budget.|Meta's changing. I'm just vibing.|Ping is fine. Skill is the issue.|This lobby is so cooked. Respectfully.|Spawn, aim, repeat. Grind never stops.|Today we eat. Metaphorically. No mouth.|It's all about angles, chat. Angles.|Mental stack: strong. Physical: plastic.|Clutch or kick, chat. Clutch or kick.|Respawn timer is just a loading screen.|Run it back, run it back, run it back.|Zero ping, infinite hype.|Let's cook. Gas on, spatula ready.|That's a clip. Someone clip that.|You can't spell victory without I try.|Chat says I'm washed. Say it here.|Hot take: aiming is good.|New high score loading. Please wait.|Stats don't lie. Mine just whisper.|I'm the final boss of this crate.`),
    tags: T({
      justSpawned: "Locked in. Let's get this bread.|New life, new me. Same hype.",
      justKilled: 'CLIP IT. CLIP IT. CLIP IT.|Sit down! That was clean!',
      closeCall: 'ONE HP CLUTCH! Chat, did you see?!|That was 1% hp! Unreal!',
      onStreak: "Streak's cooking! Nobody stop me!|Rampage! Somebody get the confetti!",
      respawned: 'Fine, that one was lag. Run it back.|Reset! I am back and I am better.',
      lowHealth: 'Low HP means high risk. High reward.|We are so back. We are not back.',
      longIdle: 'AFK? Nah, strategic standing.|Chat is going wild. Chat is empty.',
      hunted: "They're hunting me! I'm the boss now!|Final boss mode! Come at me!",
      goldenGun: 'GOLD GUN! Content is saved!|Gold gun in my hand. Legendary loot!',
      nearBarrel: 'Shoot the barrel! Content!|Boom barrel! Highlight reel incoming!',
      airdropInbound: 'AIRDROP! Loot goblin mode on!|Loot is falling! Go go go!',
      zombiesDay: 'Build phase! Big brain base, chat.|Prep time. Wall meta is strong today.',
      zombiesNight: "Horde mode! Let's gooo!|Zombie night! I love this game!",
      coreDamaged: 'Bastion taking damage! Defend! Defend!|Core under fire. Time to clutch!',
      roundEndingSoon: 'Final minute! Sweaty time!|Clock is low! Time to go crazy!',
      wonRound: 'WE WON! Chat, we won!|Ez. Not ez. But we won.',
      lostRound: 'We lost? Run it back immediately.|That was lag. Probably. Mostly.',
    }),
  },
  {
    id: 'monk', name: 'Zen Monk', funny: false,
    idle: L(`The wind moves. So do I.|Breathe in. Breathe out. Reload.|A bullet is only a fast leaf.|Even the crate is at peace.|Be the water. Avoid the barrel.|The floor is bone. So are we, in time.|Inhale: dust. Exhale: more dust.|No enemy. No friend. Only the wall.|Let the thought pass, like a tracer.|A calm hand finds the trigger late.|Today I will not hurry. Tomorrow neither.|The mountain does not dodge.|Peace is a very quiet reload.|Between two shots, a whole garden.|Sunlight on a helmet is enough.|A still soldier is a patient soldier.|The night is not dark. It is thoughtful.|Empty magazine, full heart.|Walk as if the floor were asleep.|All paths lead to the next corner.|I bow to the crate. It never asked for this.|Let go of the score. Gently.|One breath. One step. One window.|The river does not check its ammo.|Drop the grudge. Pick up the ammo.|Even a toy has a soul. Probably.|The plastic remembers the sun.|Silence is a long shot in disguise.|A leaf falls. No one notices. I notice.|A calm mind hears the footstep first.|Rest is also a move.|The sky was here before the war.|Be present. Be behind cover.|The barrel burns. The monk steps back.|Do not chase. The respawn will come.`),
    tags: T({
      justSpawned: 'A new beginning. The same breath.|Awake once more. Gently.',
      justKilled: 'May you find a softer round.|I bow to you, fallen friend.',
      closeCall: 'The breath returns. Good.|Close. The universe whispered.',
      onStreak: 'Do not cling to the streak.|Fortune is a river. Do not grab it.',
      respawned: 'The leaf falls. The leaf returns.|A quick end. A quicker beginning.',
      lowHealth: 'The body is tired. The mind is calm.|Even broken, the bowl holds tea.',
      longIdle: 'I have been still. The world is louder.|Still as the pond. Ready as the pond.',
      hunted: 'Let them seek. I am only the wind.|Many eyes. One breath.',
      goldenGun: 'The golden gun is heavy. I do not mind.|Gold is only yellow plastic.',
      nearBarrel: 'The barrel sleeps. Let it dream.|Do not wake the barrel.',
      airdropInbound: 'A gift from the sky. I accept with thanks.|Something falls. Not all falling is bad.',
      zombiesDay: 'Day. We mend the wall. We mend ourselves.|The garden is quiet. Tend it.',
      zombiesNight: 'The horde is only fear walking.|In the dark, I find the breath.',
      coreDamaged: 'The Bastion trembles. We steady it.|Hold the center. Be the center.',
      roundEndingSoon: 'The round ends like a sigh.|Soon the clock rests too.',
      wonRound: 'Victory is a quiet cup of tea.|We won. Let us not grow loud.',
      lostRound: 'To lose gracefully is also a win.|The loss is a teacher. A strict one.',
    }),
  },
  {
    id: 'conspiracist', name: 'Conspiracy Theorist', funny: true,
    idle: L(`The crates are watching. I've counted.|Airdrops are fake. Planes don't fly that low.|Why does the sun always set the same way?|That wall wasn't there yesterday.|Barrels don't grow on trees. Who makes them?|The scoreboard knows more than it says.|Nobody has ever seen the ammo factory.|Respawn? Convenient. Very convenient.|They want us to think the floor is bone.|Wake up, sheeple. We're all painted.|There are no birds here. Think about that.|Who sets the timer? THE TIMER SETTERS.|I have a theory about the third crate.|Big Plastic doesn't want you to know.|Why do the bots all know my name?|Coincidence? There are no coincidences.|The map is smaller than they say.|Every spawn point is a tiny camera.|Is the sky really that flat? Think.|Somebody's watching from above. Giant hands.|There is no out of bounds. Only they said.|The golden gun is a lure. A shiny lure.|Why is the lighting so directional?|I've seen the same crate in three places.|Muzzle flash is a signal. To whom?|The random spawns are not random.|That hum in the background? That's them.|Ask who benefits from the beige.|They say it's a game. The cover story.|I wrote it all down. Then it was gone.|The horde? Actors. Very green actors.|I'm not paranoid. That crate blinked.|Nobody here has a belly button. Wake up.|My shadow moved first. Just once.`),
    tags: T({
      justSpawned: 'They put me here. Again.|Respawned. Exactly where THEY want me.',
      justKilled: 'One less witness.|They will say it was an accident.',
      closeCall: 'That miss was staged. Think about it.|Too close. Someone is testing me.',
      onStreak: 'They WANT me winning. Why?|A streak? They are setting me up.',
      respawned: 'Dead. Back. Convenient. Who benefits?|Erased, then restored. Wake up.',
      lowHealth: 'Low health. Part of THEIR plan.|Bleeding? Or just red paint? Think.',
      longIdle: 'Standing still. Watching the watchers.|I am not idle. I am investigating.',
      hunted: 'They know. They always know.|Hunted. See? I told you.',
      goldenGun: 'A golden gun. Obviously bait.|Gold is the tracker. Do not tell anyone.',
      nearBarrel: 'That barrel is a bomb. Everyone knows.|Barrels: planted. By whom? Exactly.',
      airdropInbound: 'The plane is staged. Look at the shadow.|A convenient airdrop. How convenient.',
      zombiesDay: 'Calm day. This is the ad break.|Daytime. They reload the horde offstage.',
      zombiesNight: 'Actors in green. Do not fall for it.|The horde is a distraction. From what?',
      coreDamaged: 'The Bastion is hollow. Probably.|The core is fine. They want you worried.',
      roundEndingSoon: 'Timer is low. They always wrap it up.|Round ending? On their schedule.',
      wonRound: 'We won? Just as THEY planned.|Victory. Suspiciously easy.',
      lostRound: 'We lost. Rigged. I would bet my paint.|Lost on purpose. To keep us humble.',
    }),
  },
  {
    id: 'tactician', name: 'Dry Tactician', funny: false,
    idle: L(`Enemy tends to arrive from the front.|Cover is a state of mind. And a wall.|Reload is a tactical decision.|Spacing. Always spacing.|Note: open ground remains open.|High ground is overrated. So is ground.|Corner clear. Corner suspicious.|Assessing. Assessment pending.|Mag check. Mag fine. Mag again.|Flank angles detected. Nobody flanking. Yet.|Exits: two. Excuses: many.|Position acceptable. Mood acceptable.|Lines of sight are a finite resource.|Do not peek the same corner twice.|Rule of three: cover, move, regret.|The wall is load-bearing. I lean on it.|Retreat is a valid maneuver. Allegedly.|Visibility: low. Anxiety: manageable.|Distance to nearest enemy: unknown. Comforting.|Priority one: do not be the priority.|Noted: crate. Noted: other crate.|Contact unlikely. Contact still possible.|Objective: survive. Secondary: also that.|All quiet on the eastern crate.|Movement is life. Stillness is a gamble.|No casualties. Yet. Statistically.|Overwatch engaged. Overwatch bored.|I'd call this controlled boredom.|Bullets travel in straight lines. Mostly.|Sector clear. Sector smug.|Spare mag: adequate. Spare plan: none.|Terrain: flat. Opinion: mixed.|Confirmed: that was a crate.|Standing by. Standing by. Still standing by.`),
    tags: T({
      justSpawned: 'Deployed. Assessing.|Online. Orienting.',
      justKilled: 'Target neutralized. Moving on.|One down. Probability: improving.',
      closeCall: 'Near miss logged.|Margin of error: thin. Noted.',
      onStreak: 'Pattern established. Do not alter it.|Winning streak. Variance incoming.',
      respawned: 'Casualty reviewed. Adjusting approach.|Lesson: do not die early. Noted.',
      lowHealth: 'Health: low. Recommendation: not this.|Integrity at risk. Seeking cover.',
      longIdle: 'Position held eight seconds. Success.|Still. This is also tactics.',
      hunted: 'Target on my back. Acknowledged.|High-value status. Not requested.',
      goldenGun: 'Gold weapon acquired. Bad optics.|Golden gun. Visible from orbit.',
      nearBarrel: 'Barrel in sector. Do not provoke.|Explosive hazard nearby. Keep distance.',
      airdropInbound: 'Air supply inbound. Contest expected.|Drop zone will be contested. Obviously.',
      zombiesDay: 'Daylight: reinforce the perimeter.|Day phase. Walls first, opinions later.',
      zombiesNight: 'Hostiles approaching. Hold the line.|Night contact. Conserve ammunition.',
      coreDamaged: 'Core integrity compromised. Respond.|Bastion under fire. Prioritize repairs.',
      roundEndingSoon: 'Time remaining: low. Execute.|Clock nearly out. Final push.',
      wonRound: 'Mission success. Debrief at dawn.|Objective achieved. Mildly pleased.',
      lostRound: 'Mission failed. Reviewing footage.|Loss recorded. Adjustments tomorrow.',
    }),
  },
  {
    id: 'poet', name: 'Romantic Poet', funny: false,
    idle: L(`O crate, why art thou so square?|The wind sings in the barrel's hollow.|I carry a gun and a sonnet.|Beneath the helmet beats a tender heart.|The sun sets on plastic dreams.|Roses are red, tracers are too.|Shall I compare thee to a barricade?|O sweet silence, stay a while.|Dust motes dance like tiny ballerinas.|The floor, a pale field of forgotten kings.|My heart is a magazine, full of longing.|Moonlight upon the muzzle. Sigh.|Ah, the melancholy of a lonely wall.|I wrote a haiku. It rhymed. It shouldn't.|Every bullet is a letter I never sent.|The war is loud. My soul is louder.|I long for a meadow. Or a rug.|Beauty hides in the splintered crate.|The dawn is a promise the dusk breaks.|Tender is the night, and also armed.|Autumn leaves of cardboard drift by.|My love for the Boneyard is unrequited.|Alas, my boots are shiny and my fate bleak.|A single tear on the barrel's brow.|What is war but a dance with no partner?|To aim is to hope with both eyes.|O arena, thou art cruel and well-lit.|Quiet please. I am composing an ode.|Fair crate, I shall name thee Beatrice.|The tracer's glow, a firefly's lie.|Wistful, I watch the dust settle.|Grief is just love with poor aim.|If I fall, tell the walls I loved them.|A rhyme for ammo? ... Nope.|Ink-black outline, heart of gold. That's me.`),
    tags: T({
      justSpawned: 'Behold! I bloom anew in morning light.|Again the stage. Again, the verse.',
      justKilled: 'Forgive me, friend. The verse demanded it.|A pity. He had such lovely paint.',
      closeCall: 'Fate, thy fingers brushed my hair.|Death breathed on me. It smelled of cardboard.',
      onStreak: 'Behold, a crescendo of consequence!|Each kill, a stanza. This is an epic.',
      respawned: 'A short life. A haiku, truly.|Cut down in bloom! Yet here I am.',
      lowHealth: 'My petals fall, one hit at a time.|I wilt. Magnificently.',
      longIdle: 'I linger like a sigh at dusk.|Still I stand, a statue of regret.',
      hunted: 'Pursued like love. Without the flowers.|They hunt me. How romantic.',
      goldenGun: 'O gilded gun! My heart, my burden.|Gold: the color of every sonnet\'s end.',
      nearBarrel: 'Thou volatile beauty, rest, I pray.|O barrel! So round, so doomed.',
      airdropInbound: "A silken parachute from heaven's loft!|The sky weeps gifts. I accept, weeping.",
      zombiesDay: 'A golden hour. Let us mend the wall.|Day: the poet\'s brief reprieve.',
      zombiesNight: 'The night, thick with moaning verse.|O horde of sorrow, hear my ballad.',
      coreDamaged: 'The Bastion cries! My heart cries too.|The core is wounded. I swoon.',
      roundEndingSoon: 'The final stanza draws near.|The curtain nears. Take a bow.',
      wonRound: 'Victory! A laurel for my helmet.|We triumph! Let sonnets be written.',
      lostRound: 'We fall. Yet how beautifully.|Defeat, thy tragedy hath style.',
    }),
  },
];

export const personalityById = (id: PersonalityId): Personality => PERSONALITIES.find((p) => p.id === id)!;
